# Generated by Django 5.2.8 on 2025-11-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tree_type', models.CharField(choices=[('KAPOK', 'Kapok Tree'), ('MAHOGANY', 'Mahogany Tree'), ('RUBBER', 'Rubber Tree'), ('BRAZIL_NUT', 'Brazil Nut Tree'), ('ACAI', 'Açaí Palm'), ('COCOA', 'Cocoa Tree')], default='KAPOK', max_length=20)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('planted_at', models.DateTimeField(auto_now_add=True)),
                ('is_real_tree_planted', models.BooleanField(default=False)),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.planter')),
            ],
            options={
                'ordering': ['-planted_at'],
            },
        ),
    ]
