# Generated by Django 5.2.8 on 2025-11-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(choices=[('KAPOK', 'Kapok Tree'), ('MAHOGANY', 'Mahogany Tree'), ('RUBBER', 'Rubber Tree'), ('BRAZIL_NUT', 'Brazil Nut Tree'), ('ACAI', 'Açaí Palm'), ('COCOA', 'Cocoa Tree'), ('ROSEWOOD', 'Rosewood'), ('ANDEAN_ALDER', 'Andean Alder'), ('IRONWOOD', 'Ironwood'), ('CECROPIA', 'Cecropia')], default='KAPOK', max_length=20),
        ),
    ]
